
include:
  - project: 'norsktest/dktools'
    file: '/ci-templates/dkbuild.yml'

py27:
  extends: .testpackage
  script:
    - dk testpackage --ci --django=1.7.11 --tag=py27-dj17

py3:
  stage: test
  image: thebjorn/dktestpackage3:latest
  before_script:
    - python -V
    - pip -V
  script:
    - dk testpackage --ci --tag=py3
    - bash <(curl -s https://codecov.io/bash)
  allow_failure: true
  artifacts:
    paths:
      - build/*

coverage:
  dependencies:
    - py27
    - py3

wheel:
  dependencies:
    - py27
