language: python
sudo: false

python:
  - "2.7"
  - "3.6"

services:
  - redis-server

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  py.test -vv --cov=dkredis .

after_success:
  coveralls

